# .streamlit/secrets.toml
[pinning_services]
filebase_api_key = "YOUR_FILEBASE_KEY_HERE"
nft_storage_api_key = "YOUR_NFT_STORAGE_KEY_HERE"
pinata_api_key = "YOUR_PINATA_KEY_HERE"
infura_api_key = "YOUR_INFURA_KEY_HERE" 